name: Melbourne Evangelical Church
description: Challenging bible teaching in the heart of Melbourne, Australia.
keywords: jesus,melbourne,christianity,evangelical,bible,teaching
url: http://melbourneevangelicalchurch.com.au
service_time: 5:00pm
staticURL: https://s3-ap-southeast-2.amazonaws.com/static.melbourneevangelicalchurch.com.au/
bibleAPIKey: gn9tZo6THRRJ9fElH32uaPI1fwOgXLuSCAS8TCbf
markdown: redcarpet
highlighter: true
gems:
  - jekyll-sitemap
